name: Laravel CI/CD with Docker

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Containers
        run: |
          docker compose up -d --build

      - name: Ensure Containers Are Running
        run: |
          echo "Waiting for services to be ready..."
          sleep 10
          docker ps

      - name: Ensure MySQL is Ready
        run: |
          until docker exec doot_storage mysqladmin ping -h"mysql" --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Run Composer Install
        run: |
          docker exec doot php -d memory_limit=-1 /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader || (
            echo "Composer install failed, restarting container..."
            docker restart doot
            sleep 5
            docker exec doot php -d memory_limit=-1 /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
          )

      - name: Run Migrations & Seeders
        run: |
          docker exec doot php artisan migrate --force
          docker exec doot php artisan db:seed --force

      - name: Clear Cache & Restart Queue
        run: |
          docker exec doot php artisan config:clear
          docker exec doot php artisan cache:clear
          docker exec doot php artisan queue:restart

      - name: Restart Application
        run: docker restart doot
